### ISSUE TITLE
Model IDs?

### ISSUE THREAD

**Issue by andrewniekamp** [daviesre/seattle-scifi#1]
Thoughts on whether to use IDs on our model constructor?

If we ultimately use Firebase I suppose we don't need to, but if we use a JSON file, should we?

I guess we can add/take out later if we have different thoughts.

**Comment by RubyBe** [comment]
I think that's a good idea, i've added an id to my model. Also am using the field name "role" to represent the name of the character associated with the quote, as per andrew's model.
