### ISSUE TITLE
A good stopping point?

### ISSUE THREAD

**Issue by daviesre** [daviesre/seattle-scifi#11]
Sid suggested that we all stop at our displays/lists before doing the components that add/delete/etc. Is that okay for everyone?

**Comment by JoelWaage** [comment]
Works great for me

**Comment by andrewniekamp** [comment]
sure thing - oops, already did my add component!

**Comment by JoelWaage** [comment]
Looking forward to seeing how many times and in how many ways I can misspell the word 'movie'
